### ISSUE TITLE
Is there a way to make this extension work with Twitch?

### ISSUE THREAD

**Issue by Bloomfear** [alextrv/enhanced-h264ify#2]
Twitch is also heavy on the cpu. How can i make this extension work with twitch?

**Comment by alextrv** [comment]
Since this extension only lets you choose among offered video formats it makes no sense to make the extension work with Twitch because Twitch offers only one video format and it's h.264. Youtube offers vp9 and h.264, and for some videos vp8 and av1. That's why it can work with Youtube, but not with Twitch.
